apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-https
  namespace: monitoring
spec:
  parentRefs:
  - name: primary-gateway-shared
    sectionName: https
    namespace: default
  hostnames:
    - grafana.home.rushidarunte.com
  rules:
    - backendRefs:
        - name: grafana
          group: ''
          port: 80
          kind: Service
          weight: 1