apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: contact@rushidarunte.com
    # The ACME certificate profile
    profile: tlsserver
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        rfc2136:
          nameserver: dns.home.rushidarunte.com
          tsigKeyName: rndc-key
          tsigAlgorithm: HMACSHA256
          tsigSecretSecretRef:
            name: rfc2136-keys
            key: rfc2136-tsig-secret