apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/x64nik/homelab.git
    targetRevision: main
    path: kubernetes/helm-charts/open-webui
    helm:
      valueFiles:
        - values-inferno.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true