apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/x64nik/open-webui-helm-chart.git
      targetRevision: x64nik/feature/gateway-api-support
      path: charts/open-webui
      helm:
        valueFiles:
          - $values/kubernetes/helm-charts/open-webui/values-inferno.yaml
    - repoURL: https://github.com/x64nik/homelab.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true