apiVersion: v2
description: "A lightweight monitoring stack combining VictoriaMetrics single-node and Grafana, managed via Helm."
type: application
maintainers:
  - name: x64nik
    email: contact@rushidarunte.com
    url: https://github.com/x64nik
name: grafana-victoria-stack
version: 1.0.0
appVersion: v1.0.0

dependencies:
  - name: victoria-metrics-single
    version: "0.9.3"
    repository: https://victoriametrics.github.io/helm-charts
    condition: victoria-metrics-single.enabled
  - name: victoria-logs-single
    version: "0.11.26"
    repository: https://victoriametrics.github.io/helm-charts
    condition: victoria-logs-single.enabled
  - name: victoria-logs-collector
    version: "0.2.9"
    repository: https://victoriametrics.github.io/helm-charts
    condition: victoria-logs-collector.enabled 
  - name: victoria-traces-single
    version: "0.0.6"
    repository: https://victoriametrics.github.io/helm-charts
    condition: victoria-traces-single.enabled

  - name: grafana
    version: "10.5.5"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled