{{- if .Values.global.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "app.fullname" . }}-gateway
  {{- with .Values.global.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ .Values.global.gateway.gatewayClassName }}
  listeners:
  {{- range .Values.global.gateway.listeners }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: {{ .protocol }}
    {{- with .hostname }}
    hostname:
    {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- if .allowedRoutes }}
    allowedRoutes:
      {{- toYaml .allowedRoutes | nindent 6 }}
    {{- end }}
    {{- if eq .protocol "HTTPS" }}
    tls:
      mode: {{ .tls.mode | default "Terminate" }}
      certificateRefs:
      {{- range .tls.certificateRefs }}
      - name: {{ .name }}
        {{- if .namespace }}
        namespace: {{ .namespace }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}