apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: wildcard-home-ci
spec:
  acme:
    # ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email for Let's Encrypt notifications
    email: contact@rushidarunte.com
    # Secret to store ACME account private key
    privateKeySecretRef:
      name: wildcard-home-ci-acme-key
    solvers:
    # Cloudflare DNS-01 challenge
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token