apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: primary-gateway-class
  # No namespace - GatewayClass is cluster-scoped
spec:
  controllerName: io.cilium/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: jellyfin-gateway
  namespace: myflix
spec:
  gatewayClassName: primary-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: myflix
spec:
  parentRefs:
  - name: jellyfin-gateway
  hostnames:
  - "myflix2.home.rushidarunte.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    backendRefs:
    - name: jellyfin
      port: 8096